apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080/
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: minikube
    registry: 10.103.224.16
  environments:
  - key: dev
    owner: Nathan-Smith
    repository: jx3-testing
  - key: staging
  - key: production
  ingress:
    domain: 192.168.49.2.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: Nathan-Smith
  repository: none
  secretStorage: local
  vault: {}
  webhook: lighthouse
