filepath: ""
namespace: jx-production
repositories:
- name: dev
  url: http://bucketrepo-jx.192.168.49.2.nip.io
releases:
- chart: dev/jx3-spring-boot-test
  version: 0.0.5
  name: jx3-spring-boot-test
templates: {}
renderedvalues: {}
